name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debate-app-validate:
    name: Debate App Validate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install dependencies
      working-directory: debate-app
      run: npm ci
      
    - name: Debug - Show installed packages
      working-directory: debate-app
      run: npm list --depth=0
    
    - name: Check code formatting
      working-directory: debate-app
      run: npm run format:check || (echo "Formatting check failed. Run 'npm run format' to fix" && exit 1)
    
    - name: Lint
      working-directory: debate-app
      run: npm run lint || (echo "Linting failed. Run 'npm run lint:fix' to fix" && exit 1)
    
    - name: Type check
      working-directory: debate-app
      run: npx tsc --noEmit || (echo "Type checking failed. Fix type errors and try again" && exit 1)
    
    - name: Run tests
      working-directory: debate-app
      run: npm test
      
  debate-app-build:
    name: Debate App Build
    needs: debate-app-validate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install dependencies
      working-directory: debate-app
      run: npm ci
    
    - name: Build application
      working-directory: debate-app
      run: npm run build
      
    - name: Debug - List build directory
      working-directory: debate-app
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Build directory contents:"
        ls -la build || echo "Build directory not found"
    
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: debate-app-build
        path: debate-app/build
        retention-days: 7

  debate-app-security:
    name: Debate App Security
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install dependencies
      working-directory: debate-app
      run: npm ci
    
    - name: Run npm audit
      working-directory: debate-app
      run: npm audit --audit-level=high || true 